/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package week_02;

import javax.swing.*;
import java.io.*;
import java.nio.charset.StandardCharsets;

public class frm_RC4 extends javax.swing.JFrame {
    private RC4Cipher rc4;
    public frm_RC4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Plaintext = new javax.swing.JTextField();
        txt_key = new javax.swing.JTextField();
        txt_Ciphertext = new javax.swing.JTextField();
        btn_encrypt = new javax.swing.JButton();
        btn_decrypt = new javax.swing.JButton();
        btn_savefile = new javax.swing.JButton();
        btn_openfile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("RC4 Cipher Demo");

        jLabel2.setText("Plaintext");

        jLabel3.setText("key");

        jLabel4.setText("Ciphertext");

        btn_encrypt.setText("Encrypt");
        btn_encrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encryptActionPerformed(evt);
            }
        });

        btn_decrypt.setText("Decrypt");
        btn_decrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_decryptActionPerformed(evt);
            }
        });

        btn_savefile.setText("Save to File");
        btn_savefile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_savefileActionPerformed(evt);
            }
        });

        btn_openfile.setText("Open File");
        btn_openfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btn_encrypt)
                        .addGap(37, 37, 37)
                        .addComponent(btn_decrypt)
                        .addGap(18, 18, 18)
                        .addComponent(btn_savefile)
                        .addGap(18, 18, 18)
                        .addComponent(btn_openfile))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_Ciphertext, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(txt_key)
                            .addComponent(txt_Plaintext))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_Plaintext, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Ciphertext, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_decrypt)
                        .addComponent(btn_savefile)
                        .addComponent(btn_openfile))
                    .addComponent(btn_encrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_encryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encryptActionPerformed
        String plaintext = txt_Plaintext.getText();
        byte [] plaintextBytes = plaintext.getBytes(StandardCharsets.UTF_8);
        String key =txt_key.getText();
        rc4 = new RC4Cipher(key.getBytes());
        byte[] ciphertextBytes = rc4.encrypt(plaintextBytes);
        String ciphertext = bytesToHexString(ciphertextBytes);
        txt_Ciphertext.setText(ciphertext);
        
    }//GEN-LAST:event_btn_encryptActionPerformed

    private void btn_decryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_decryptActionPerformed
       String ciphertext = txt_Ciphertext.getText();
       byte[] ciphertextBytes = hexStringToByteArray(ciphertext);
       String key =txt_key.getText();
       rc4 = new RC4Cipher(key.getBytes());
       byte[] decryptedBytes = rc4.decrypt(ciphertextBytes);
       String decryptedText = new String(decryptedBytes,StandardCharsets.UTF_8);
       txt_Plaintext.setText(decryptedText);
    }//GEN-LAST:event_btn_decryptActionPerformed

    private void btn_savefileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_savefileActionPerformed
        String ciphertext = txt_Ciphertext.getText();
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save ciphertext to File");
        int userSelection = fileChooser.showSaveDialog(this);
        if(userSelection == JFileChooser.APPROVE_OPTION ){
            File fileToSave = fileChooser.getSelectedFile();
            try
                (FileWriter writer = new FileWriter(fileToSave.getAbsolutePath()+ ".txt")){
                writer.write(ciphertext);
                JOptionPane.showMessageDialog(this, 
                        "Ciphertext saved to file successfully.",
                        "Success" ,JOptionPane.INFORMATION_MESSAGE);
            }catch(IOException e){
                    JOptionPane.showMessageDialog(this,"Error saving file:"+ e.getMessage(),
                            "Error",JOptionPane.ERROR_MESSAGE);
                    }
            }

        

    }//GEN-LAST:event_btn_savefileActionPerformed

    private void btn_openfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openfileActionPerformed
       JFileChooser fileChooser = new JFileChooser();
       fileChooser.setDialogTitle("open file containing ciphertext");
        int userSelection = fileChooser.showOpenDialog(this);
        if(userSelection == JFileChooser.APPROVE_OPTION ){
            File fileToOpen = fileChooser.getSelectedFile();
            try
               (BufferedReader reader = new BufferedReader (new FileReader(fileToOpen))){
            StringBuilder ciphertextBuilder = new StringBuilder();
            String line;
           while ((line = reader.readLine()) != null){
            ciphertextBuilder.append(line);
}
           String ciphertext = ciphertextBuilder.toString().trim();
           txt_Ciphertext.setText(ciphertext);
     }catch (IOException e){
      JOptionPane.showMessageDialog(this,"Error opening file:" + e.getMessage(),
            "Error",JOptionPane.ERROR_MESSAGE);
}
}
    }//GEN-LAST:event_btn_openfileActionPerformed
private static byte[] hexStringToByteArray(String s){
     int len= s.length();
     byte[] data = new byte [len/2];
     for(int i=0;i<len;i+=2){
       data[i/2] = (byte)((Character.digit(s.charAt(i),16)<<4)
             + Character.digit(s.charAt(i+1), 16));
}
return data;
}
private static String bytesToHexString(byte[] bytes){
     StringBuilder  sb = new StringBuilder();
for(byte b:bytes){
   sb.append(String.format("%02X", b));
}
return sb.toString();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_RC4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_RC4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_RC4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_RC4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_RC4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_decrypt;
    private javax.swing.JButton btn_encrypt;
    private javax.swing.JButton btn_openfile;
    private javax.swing.JButton btn_savefile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_Ciphertext;
    private javax.swing.JTextField txt_Plaintext;
    private javax.swing.JTextField txt_key;
    // End of variables declaration//GEN-END:variables

}